spawn:
  location: "world,0,21,0,180.0,2.0"
  bedSpawn: true
portals:
  enabled: true
  require-modreq: true
  disable-destination-build: true
warpzones: []
  #spawnZone:
  #  ==: at.junction.omneity3.WarpZone
  #  minFrom: world|0|64|0
  #  maxFrom: world|1|66|1
  #  to: world|100|65|100|90|180
firstjoin:
  firstJoinMessageEnabled: true
  firstJoinMessage: "%sWelcome %s to the server!"
  itemsEnabled: false
  items:
  - 32xBREAD
swap-server: chaos
pet-kill-disabled: true
recipes:
  furnace:
    mossy-cobblestone:
      ==: at.junction.omneity3.recipes.Furnace
      result: STONE
      source: MOSSY_COBBLESTONE
  shaped:
    diamond-barding:
      ==: at.junction.omneity3.recipes.Shaped
      shape: "  A-ASA-AAA"
      ingredients:
      - A|DIAMOND
      - S|SADDLE
      result: DIAMOND_BARDING
      count: 1
    gold-barding:
      ==: at.junction.omneity3.recipes.Shaped
      shape: "  A-ASA-AAA"
      ingredients:
      - A|GOLD_INGOT
      - S|SADDLE
      result: GOLD_BARDING
      count: 1
    iron-barding:
      ==: at.junction.omneity3.recipes.Shaped
      shape: "  A-ASA-AAA"
      ingredients:
      - A|IRON_INGOT
      - S|SADDLE
      result: IRON_BARDING
      count: 1
  shapeless:
    mossy-cobblestone:
      ==: at.junction.omneity3.recipes.Shapeless
      ingredients:
      - VINE
      - COBBLESTONE
      result: MOSSY_COBBLESTONE
      count: 1