spawn:
  location: "world,0,21,0,180.0,2.0"
  bedSpawn: true
portals:
  enabled: true
  require-modreq: true
  disable-destination-build: true
warpzones:
  #spawnZone:
  #  ==: at.junction.omneity3.WarpZone
  #  minFrom: world|0|64|0
  #  maxFrom: world|1|66|1
  #  to: world|100|65|100|90|180
firstjoin:
  firstJoinMessageEnabled: true
  firstJoinMessage: "%sWelcome %s to the server!"
  itemsEnabled: false
  items:
  - 32xBREAD
swap-server: chaos
pet-kill-disabled: true