name: Omneity3
version: 0.1
description: All-comprehensive catch-all plugin for junction.at servers. Based off of original Omneity Python Plugin.
author: zifnab06
website: http://github.com/junctionat/Omneity3

main: at.junction.omneity3.Omneity3
database: false

commands:
  spawn:
    description: Teleport to spawn
    permission: omneity.spawn
    usage: /spawn
  o3-reload:
    description: Reload config
    permission: omneity.tech
    usage: /o3-reload
  world:
    description: World teleportation
    permission: omneity.world
    usage: /world <name> [<x> <y> <z>]. Valid names are 'world', 'world_nether' and 'world_the_end'.
  coords:
    description: Print player's coordinates
    permission: omneity.coords
    usage: /coords
  item:
    description: Give player an item
    aliases: [i]
    permission: omneity.aliases
    usage: /i <item>[:data] [amount]
  staffchest:
    description: Lock a chest to staff
    permission: omneity.aliases
    usage: /staffchest
  unstaff:
    description: Remove staff perms on chest
    permission: omneity.aliases
    usage: /unstaff
  trace:
    description: Trace player's block edits
    permission: omneity.aliases
    usage: /trace <playername>
  tppos:
    description: Teleport player to coordinate
    permission: omneity.aliases
    usage: /tppos [<world>] <x> <y> <z>
  entity-magnet:
    description: Allows player to become a magnet for entities
    permission: omneity.magnet
    usage: /entity-magnet <entity-name>
  swap-player:
    description: Swap player to server
    permission: omneity.swap
    usage: /swap-player player server
  give-pet:
    description: Give a player a pet
    permission: omneity.pet
    usage: /give-pet new-owner
permissions:
  omneity.spawn:
    description: Usage of /spawn command
    default: op
  omneity.world:
    description: Usage of /world command
    default: op
  omneity.portal:
    description: Allows player to place portals
    default: op
  omneity.coords:
    description: Usage of /coords command
    default: true
  omneity.aliases:
    description: Use of aliases. Permissions dealt with based on commands being run through dispatch.
    default: true
  omneity.magnet:
    description: Entity Magnet!
    default: op
  omneity.swap:
    description: /swap-player usage
    default: op
  omneity.give-pet:
    description: Give players pets!
    default: op