name: Omneity3
version: 0.1
description: All-comprehensive catch-all plugin for junction.at servers. Based off of original Omneity Python Plugin.
author: zifnab06
website: http://github.com/junctionat/Omneity3

main: at.junction.omneity3.Omneity3
database: false

commands:
  spawn:
    description: Teleport to spawn
    permission: omneity.spawn
    usage: /spawn
  o3-reload:
    description: Reload config
    permission: omneity.tech
    usage: /o3-reload
  world:
    description: World teleportation
    permission: omneity.world
    usage: /world <name> [<x> <y> <z>]. Valid names are 'world', 'world_nether' and 'world_the_end'.
  coords:
    description: Print player's coordinates
    permission: omneity.coords
    usage: /coords
  item:
    description: Give player an item
    aliases: [i]
    usage: /i <item>[:data] [amount]
permissions:
  omneity.spawn:
    description: Usage of /spawn command
    default: op
  omneity.world:
    description: Usage of /world command
    default: op
  omneity.portal:
    description: Allows player to place portals
    default: op
  omneity.coords:
    description: Usage of /coords command
    default: true